// PROGRAMMING LANGUAGE = TYPESCRIPT
// CODE CONTENT STRUCTURE
// -> STRUCTURED AND WELL DEFINED LANGUAGE
// IMPORTING LIBRARIES
// PRIMARY (IMPORTANT, CORE)
import mongoose from "mongoose"
// MONGOOSE.JS DOCUMENTATION :
// DEVELOPER GUIDES :
// IMPORTANT STANDARD CONCEPTS :
// 1. SCHEMA (GENERAL STANDARD CONCEPT)
// 2. MODEL (GENERAL STANDARD CONCEPT)
// 3. DEFINING FIELDS OF A MODEL
// 4. ENTITY DEFINITION = SET<FIELDS / ATTRIBUTES>
// 5. FIELD TYPES (GLOBAL STANDARD CONCEPT)
// 6. SCHEMA PATH (MONGOOSE SPECIFIC CONCEPT)
// 7. COLLECTION = TABLE = ENTITY (MONGOOSE SPECIFIC CONCEPT)
// 8. DOCUMENT = RECORD = INSTANCE (MONGOOSE SPECIFIC CONCEPT)
/*
- CHARACTER = ASCII VALUE = INTEGER = SYMBOL
1. STRING = SEQUENCE<CHARACTERS>
2. NUMBER = QUANTITY (INTEGERS, REAL-NUMBERS)
3. DATE = YEAR + MONTH + DATE + DAY + HOUR + MINUTES + SECONDS = NUMBER OF MILLISECONDS
4. BUFFER = GENERAL PURPOSE FILE STORAGE = ARAY OF CONTAGIOUS MEMORY = MODULAR ACCESS
5. BOOLEAN = FLAG = MOST FUNDAMENTAL PRIMITIVE DATA TYPE
6. MIXED = AMBIGIOUS DATA = SCHEMA-LESS TYPE = PRIMITIVE OR HIGHER-LEVEL DATA TYPE
7. OBJECT-ID = SPECIAL TYPE = UNIQUE INDENTIFIER OF THE RECORD = INDEXING (DATABASE SUBJECT CONCEPT)
    - DIFFERENT TYPES OF ID FIELDS
    - COMPOUND INDEX
8. ARRAY : LIST OF ELEMENTS OF SAME DATA TYPE
9. DECIMAL-128 : FLOATING POINT NUMBER
10. MAP : DICTIPNARY
11. UUID : UNIVERSILLAY UNIQUE IDENTIFER
*/
// FIELD / AREA OF STUDY : 
// 1. COMPUTER SCIENCE AND ENGINEERING
// 2. INFORMATION TECHNOLOGY
// 3. SOFTWARE DEVELOPMENT
// 4. SOFTWARE ENGINEERING
// POPULAR / TRADITIONAL JOB TITLES 
// CREATIVE LEVEL JOBS
// RESEARCH AND DEVELOPMENT
// BUSINESS LOGIC IMPLEMENTATION IN DATABASE
// FIELD / SUBJECT : DATABASE MANAGEMENT SYSTEMS
// 1. DABASE SYSTEMS DESIGN
// 2. DATABASE ADMINISTRATION
// ----------------------------------------------------
// RELATED ENTITY KEYWORDS
// 1. CODE-BLOCK
// 2. CODE-CHUNK
// 3. SMALL-PROJECT
// 4. PROGRAM
// 5. COMPLETE PROGRAM
// 6. CODE THING
// DOMAIN SPECIFIC KNOWLEDGE
// THE PRIMARY BUSINESS STRUCTURE
// THE CUSTOMER STORIES
// THE PROBLEMS AND DETAILS
// THE ACTUAL PROBLEM / WORKING ENVOIRNMENT
const schema_CodeSnippet = new mongoose.Schema({

});